backend:
  name: git-gateway
  branch: cms
media_folder: 'public/assets/uploads'
public_folder: '/assets/uploads'
collections:
  - name: 'writing'
    label: 'Blog'
    folder: 'eleventy/writing'
    create: true
    slug: '{{slug}}'
    fields: # The fields for each document, usually in front matter
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Description', name: 'description', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
